insert into logistic.product (depth, height, width, category, description, id, name, restrictions, storage_instructions)
values (60, 0.5, 50, 'CLOTHING_AND_APPAREL', 'Blusa confortável em algodão puro.', 'NZAY4KDRMRSN38N32FCGZ9ZLFZBUK7',
        'Blusa de Algodão', 'Evite alvejantes.', 'Lave antes de usar. Mantenha em local fresco.'),
       (4.5, 0.8, 4.5, 'JEWELRY_AND_WATCHES', 'Relógio elegante à prova d''água.', 'ESWQ62EWUF7WXDBBWLGGN7BAEZGSNQ',
        'Relógio de Pulso', 'Resistente à água até 30m.', 'Evite contato com produtos químicos.'),
       (10, 1, 15, 'CLOTHING_AND_APPAREL', 'Camisa macia e confortável para uso diário.',
        'Y58APQXDC2P24MUJGDUUQMW58R46VB', 'Camisa de Algodão', 'Evite usar ferro muito quente.',
        'Lave com cores semelhantes e seque à sombra.'),
       (14, 2.5, 20, 'BOOKS_AND_PUBLICATIONS', 'Coletânea de receitas tradicionais brasileiras.',
        'AMLBHPAQF7GTMC95ZLXCWSBR8JBT57', 'Livro de Receitas', 'Nenhuma.',
        'Mantenha longe da umidade e da luz direta do sol.'),
       (20, 3, 28, 'TOYS_AND_GAMES', 'Quebra-cabeça de 1000 peças com imagens temáticas.',
        '29TU6ALL7ELZGX4BVVWYJEHQASHJH6', 'Quebra-Cabeça Temático',
        'Não recomendado para crianças menores de 3 anos devido a peças pequenas.',
        'Guarde em local seco e longe de pequenos animais e crianças.'),
       (15, 3, 45, 'COMPUTERS_AND_PERIPHERALS', 'Teclado mecânico com retroiluminação RGB.',
        '6MMNBWH4MPUTPNV7WHQETAKMZFHCXV', 'Teclado Mecânico', 'Evite impactos.', 'Mantenha limpo e longe de líquidos.'),
       (20, 5, 15, 'HOME_APPLIANCES', 'Conjunto de talheres para seis pessoas.', '5KYRWCVWLEF8N3ETJQT8HQ8W4KFEET',
        'Talheres de Aço Inox', 'Não usar em micro-ondas.', 'Lave antes de usar.'),
       (10, 5.5, 5, 'PERISHABLES', 'Brócolis orgânico fresco para refeições saudáveis.',
        'BQT6M9PGTMLN4GC6D45GAT7JKCBBP4', 'Brócolis Orgânico', 'Consumir dentro de uma semana após a compra.',
        'Mantenha refrigerado para maior durabilidade.'),
       (3, 6, 6, 'CANNED_FOOD', 'Atum conservado em água e sal.', 'TGGYGJ8LR8QBSBKYG7TUWVJHE2R33B', 'Atum em Lata',
        'Contém peixe.', 'Mantenha em local fresco e seco. Após aberto, consumir imediatamente.'),
       (10, 7.5, 20, 'BUILDING_MATERIALS', 'Tijolos de alta resistência para construção.',
        'C859FW8G72LJQST4BJQKDKQQJ4LU2Z', 'Tijolos Refratários', 'Use equipamento de proteção ao manusear.',
        'Mantenha em local seco e protegido da chuva.'),
       (5, 10, 15, 'MEDICAL_SUPPLIES', 'Kit contendo itens essenciais para primeiros socorros.',
        '4HBVZ9METLHWNT8ZKY5A4ALT7LVMWT', 'Kit Primeiros Socorros', 'Use apenas conforme indicado.',
        'Mantenha em local acessível e longe do alcance de crianças.'),
       (10, 10, 15, 'CAMERAS_AND_PHOTOGRAPHY', 'Câmera digital profissional.', '47MYF952U9E5VJNU68G72WKPHZR5TK',
        'Câmera DSLR', 'Evite exposição prolongada ao sol.', 'Mantenha em local seco e use uma capa protetora.'),
       (30, 10, 20, 'SPORTING_EQUIPMENT', 'Tênis para corrida e atividades físicas.', 'VV8MQ923C2T3JPSCVS6LAD675E6QFW',
        'Tênis Esportivo', 'Verifique o tamanho adequado.', 'Deixe secar após o uso.'),
       (10, 10.5, 10, 'ELECTRONICS', 'CPU topo de linha para jogos e uso profissional.',
        '7KUKZ7BA64VXN5MDG997E7P2R4F235', 'CPU de Alta Performance', 'Sensível à eletricidade estática.',
        'Armazenar longe de ímãs e áreas de alta temperatura.'),
       (35, 12, 25, 'SPORTING_EQUIPMENT', 'Tênis projetado para jogadores de basquete.',
        'KNHYBWEC9L5YGWPK37BLKY9P2AB8WJ', 'Tênis de Basquete', 'Uso esportivo.', 'Limpe com um pano úmido.'),
       (5, 13, 5, 'HEALTH_SUPPLEMENTS', 'Suplemento de vitamina C.', 'NNFEZY9DH2TNRVDJNTV3TGWXNTPVQ9',
        'Suplemento Vitamínico C', 'Siga a dosagem recomendada.', 'Mantenha em local fresco e longe da luz solar.'),
       (5, 15, 5, 'BEAUTY_AND_PERSONAL_CARE', 'Perfume com notas florais e frutais.', '84YZ3MEBN3F2GLNCNFCTEXZCMZ5B74',
        'Perfume Floral', 'Uso externo.', 'Mantenha longe da luz solar direta.'),
       (7, 15, 7, 'ART_AND_CRAFT_SUPPLIES', 'Tinta acrílica de secagem rápida.', 'VFL7CA8773G5LVVFS96ZRVWW8CKMQ5',
        'Tinta Acrílica Azul', 'Inflamável.', 'Mantenha bem fechado em local fresco.'),
       (10, 20, 30, 'AUTOMOTIVE', 'Peças genuínas para modelos de automóveis populares.',
        'WTYYXNQRFWBKV8LR2MEG3YZF8ZMVF4', 'Peças de Carro A4',
        'Certifique-se de compatibilidade com o modelo do veículo.', 'Armazene em local seco.'),
       (5, 20, 10, 'CHEMICALS', 'Removedor de tinta de alta qualidade.', 'NYMQHSNTKHKDH5USHYGNXKACJZ5AEL',
        'Removedor de Tinta', 'Mantenha longe do alcance de crianças e animais de estimação.',
        'Mantenha em local fresco e bem ventilado.'),
       (5, 20, 5, 'BEAUTY_AND_PERSONAL_CARE', 'Shampoo para todos os tipos de cabelo.',
        'YN9TJ9LLG5UUSCCWVASLADS4YB9EW2', 'Shampoo Hidratante', 'Uso externo.', 'Evite contato com os olhos.'),
       (8, 25, 8, 'FOOD_INGREDIENTS', 'Azeite extra virgem prensado a frio.', '997492FWL647AQXLJ5V5BPKMEW4NGS',
        'Azeite de Oliva', 'Evite calor excessivo.', 'Mantenha em local fresco e ao abrigo da luz.'),
       (20, 40, 20, 'KITCHEN_APPLIANCES', 'Liquidificador de alta potência com várias velocidades.',
        '3P7Q2SUJKXJZ9MJB4LEBBGBHY6BSJ6', 'Liquidificador Elétrico', 'Manuseie com cuidado.',
        'Desligue da tomada quando não estiver em uso.'),
       (20, 60, 35, 'SPORTS_AND_OUTDOOR_GEAR', 'Mochila resistente para caminhadas longas.',
        'FFEPFBDMWLNYPDD5AR9PTVKM228ZLX', 'Mochila de Trilha', 'Limite de peso de 15 kg.',
        'Mantenha em local seco. Limpe após cada uso.'),
       (75, 75, 150, 'OFFICE_FURNITURE', 'Mesa espaçosa para ambiente de trabalho.', 'KL2P7PFQUF99SGG7GEA6SYTMUHXE27',
        'Mesa de Escritório xx', 'Requer montagem.', 'Limpe regularmente com pano seco.'),
       (10, 100, 35, 'MUSIC_INSTRUMENTS', 'Guitarra acústica de seis cordas.', 'CAGXG7AMPJ9HA5QX3MZFKH7Z83WEQZ',
        'Guitarra Acústica', 'Evite impactos e quedas.', 'Mantenha em local seco e use uma capa.'),
       (170, 100, 50, 'CYCLING_EQUIPMENT', 'Bicicleta projetada para trilhas e terrenos irregulares.',
        '46Z6FL2NF95QVYT6388CYWRKY97NXR', 'Bicicleta de Montanha', 'Requer montagem.',
        'Mantenha em local seco. Evite exposição prolongada ao sol.');